version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6901ag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh 
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  spotify_backend:
    build: .
    container_name: app_spotify
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: spotify
      DB_USERNAME: postgres
      DB_PASSWORD: 6901ag
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./.env:/app/.env     # <-- Gắn mount file .env đúng vị trí trong service
    command: ["/app/build/bin/server"]
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
  redis_data:
