version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    environment:
      TZ: Asia/Ho_Chi_Minh
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Ho_Chi_Minh
    networks:
      - my_network

  spotify_backend:
    build: .
    container_name: app_spotify
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      
      - ./.env:/app/.env
    command: ["/app/build/bin/server"]
    networks:
      - my_network
    tty: true 
networks:
  my_network:

volumes:
  postgres_data:
  redis_data:
