version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6901ag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh 
    networks:
      - my_network

  spotify_backend:
    build: .
    container_name: app_spotify
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    working_dir: /app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: spotify
      DB_USER: postgres
      DB_PASSWORD: 6901ag
      JWT_SECRET: "ded485eb5d74090cc81fa158716bb11e56d4844182c39a752f95f6c3f6b1f38d"
    command: ["/app/build/bin/server"]
    networks:
      - my_network

networks:
  my_network:
volumes:
  postgres_data: