name: dart_spotify
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloudinary_api: ^1.1.0
  cloudinary_url_gen: ^1.7.0
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.1.1
  dbcrypt: ^2.0.0
  dotenv: ^4.2.0
  email_validator: ^3.0.0
  googleapis_auth: ^1.6.0
  http: ^1.3.0
  image: ^4.5.4
  jwt_decoder: ^2.0.1
  mailer: ^6.4.1
  path_provider: ^2.1.5
  postgres: ^3.5.4
  redis: ^4.0.0
  strings: ^3.2.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0
